version: '3.8'

services:
  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app:cached
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    depends_on:
      - backend

  backend:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
